### ISSUE TITLE
Cleanly bypass empty histories

### ISSUE THREAD

**Issue by ts724** [AEADataEditor/processing-jira-process-data#13]
Program 01_download_issues.py crashed with an "Index Error: List out of range" message because AEAREP-5771 didn't have any history of modification. Worked around it for now (manually generating a history by making an edit to a field in JIRA) but should resolve it in the code.

**Comment by larsvilhuber** [comment]
@ts724 is this done?

**Comment by ts724** [comment]
@larsvilhuber The code didn't crash or indicate an error so this issue didn't appear to affect other cases. Any suggestions on how I could ensure this is true?

**Comment by larsvilhuber** [comment]
Then that's what you say to close it for now.


--
Lars Vilhuber, Economist
Cornell University
p: +1.607-330-5743
https://calendly.com/larsvilhuber
My working day may not be your working day. Please respond during your working day.
________________________________
