### ISSUE TITLE
Re-factor to use Python + API to extract data programmatically.

### ISSUE THREAD

**Issue by larsvilhuber** [AEADataEditor/processing-jira-process-data#3]

**Comment by larsvilhuber** [comment]
See #5

**Comment by larsvilhuber** [comment]
@wlinda1412 I've added the Python download. The file I downloaded (takes 30 minutes) is in Box (see new README-JIRA.md). Can you test whether the rest of the code works, and if not, adapt it?

**Comment by larsvilhuber** [comment]
@wlinda1412 Please continue the debugging for the Assignee in a branch. The assignee is not critical for downstream processing. I will continue on that.

**Comment by wlinda1412** [comment]
@larsvilhuber Will do. I think I have just fixed the issue. I will go ahead and make a branch and push the fix there.

**Comment by larsvilhuber** [comment]
By redefining the new default to `main`, this is now done.
